CONCURRENCY=4			# number of processes to run at once
BLOCKSIZE=512			# size in bytes of blocks to train
SAMPLING=50			# percentage of blocks to sample
MAXSAMPLES=10000		# maximum number of blocks to sample per file
MAXSAMPLESPERFILE=1000		# number of samples for each type
MODEL=$(VECTORSC).model


